version: "3.9"

services:
  app:
    image: sham1ko/devops-golang:latest # Используем готовый Docker image
    container_name: my-go-app
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=production
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce # Контейнер с Portainer
    container_name: portainer
    ports:
      - "9000:9000" # Порт для веб-интерфейса Portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
