name: Build and Push Docker Image

on:
  workflow_run:
    workflows: ["Go Tests"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t sham1ko/devops-golang:latest .

      - name: Push Docker image to Docker Hub
        run: docker push sham1ko/devops-golang:latest
