name: Build Docker Image

on:
  workflow_run:
    workflows: ["Go Tests"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t my-go-app .
